version: '3.4'

# This is an example docker-compose file for IPFS Cluster
# It runs two Cluster peers (cluster0, cluster1) attached to two
# IPFS daemons (ipfs0, ipfs1).
#
# It expects a "compose" subfolder as follows where it will store configurations
# and states permanently:
#
# compose/
# |-- cluster0
# |-- cluster1
# |-- ipfs0
# |-- ipfs1
#
# 
# During the first start, default configurations are created for all peers.

services:

##################################################################################
##################################################################################
## Cluster PEER 0 ################################################################
##################################################################################

  ipfs0:
    container_name: ipfs0
    image: ipfscors:1.0
    ports:
          - "4001:4001" # ipfs swarm
          - "4002:4002/udp" # udp swarm
          - "5001:5001" # expose if needed/wanted
#         - "8080:8080" # exposes if needed/wanted
    volumes:
      - ./compose/ipfs0:/data/ipfs
#    entrypoint:
#      - "/sbin/tini"
#      - "--"
#      - "/usr/local/bin/start_ipfs"
#    command: >
#      cmd=daemon --migrate=true
#      sh -c 'ipfs config --json API.HTTPHeaders.Access-Control-Allow-Origin '["*"]'
#      && ipfs config --json API.HTTPHeaders.Access-Control-Allow-Methods '["GET", "POST"]'
#      && ipfs config --json API.HTTPHeaders.Access-Control-Allow-Headers '["Authorization"]'
#      && ipfs daemon --migrate=true
#      /usr/local/bin/start_ipfs $$cmd
#      '
  cluster0:
    container_name: cluster0
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs0
    environment:
      # Change this! Same for all peers!
      CLUSTER_SECRET: adc72159e0ce63350c13de6a5e4d3b2f500232a770cb8c3e7829fc514d89d111 
      IPFS_API: /dns4/ipfs0/tcp/5001
    ports:
          - "9094:9094"
          - "9095:9095"
          - "9096:9096" # Cluster IPFS Proxy endpoint
    volumes:
      - ./compose/cluster0:/data/ipfs-cluster
##################################################################################
##################################################################################
## Cluster PEER 1 ################################################################
##################################################################################
      
  ipfs1:
    container_name: ipfs1
    image: ipfscors:1.0
    ports:
          - "4101:4001" # ipfs swarm
          - "4102:4002/udp" # udp swarm
#         - "5101:5001" # expose if needed/wanted
#         - "8180:8080" # exposes if needed/wanted
    volumes:
      - ./compose/ipfs1:/data/ipfs

  # cluster1 bootstraps to cluster0 if not bootstrapped before
  cluster1:
    container_name: cluster1
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - cluster0
      - ipfs1
    environment:
      # Change this! Same for all peers!
      CLUSTER_SECRET: adc72159e0ce63350c13de6a5e4d3b2f500232a770cb8c3e7829fc514d89d111
      IPFS_API: /dns4/ipfs1/tcp/5001
    ports:
          - "9194:9094" # API
#         - "9196:9096" # Cluster IPFS Proxy endpoint
    volumes:
      - ./compose/cluster1:/data/ipfs-cluster
    entrypoint:
      - "/sbin/tini"
      - "--"
    # Translation: if state folder does not exist, find cluster0 id and bootstrap
    # to it.
    command: >
      sh -c '
        cmd="daemon --upgrade"
        if [ ! -d /data/ipfs-cluster/raft ]; then
          while ! ipfs-cluster-ctl --host /dns4/cluster0/tcp/9094 id; do
            sleep 1
          done
          pid=`ipfs-cluster-ctl --host /dns4/cluster0/tcp/9094 id | grep -o -E "^(\w+)"`
          sleep 10
          cmd="daemon --bootstrap /dns4/cluster0/tcp/9096/ipfs/$$pid"
        fi
        /usr/local/bin/entrypoint.sh $$cmd
      '
##################################################################################
##################################################################################
## Cluster PEER 2 ################################################################
##################################################################################
      
  ipfs2:
    container_name: ipfs2
    image: ipfscors:1.0
    ports:
          - "4201:4001" # ipfs swarm
          - "4202:4002/udp" # udp swarm
#         - "5101:5001" # expose if needed/wanted
#         - "8180:8080" # exposes if needed/wanted
    volumes:
      - ./compose/ipfs2:/data/ipfs

  # cluster1 bootstraps to cluster0 if not bootstrapped before
  cluster2:
    container_name: cluster2
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - cluster0
      - ipfs2
    environment:
      # Change this! Same for all peers!
      CLUSTER_SECRET: adc72159e0ce63350c13de6a5e4d3b2f500232a770cb8c3e7829fc514d89d111
      IPFS_API: /dns4/ipfs2/tcp/5001
    ports:
          - "9294:9094" # API
#         - "9196:9096" # Cluster IPFS Proxy endpoint
    volumes:
      - ./compose/cluster2:/data/ipfs-cluster
    entrypoint:
      - "/sbin/tini"
      - "--"
    # Translation: if state folder does not exist, find cluster0 id and bootstrap
    # to it.
    command: >
      sh -c '
        cmd="daemon --upgrade"
        if [ ! -d /data/ipfs-cluster/raft ]; then
          while ! ipfs-cluster-ctl --host /dns4/cluster0/tcp/9094 id; do
            sleep 1
          done
          pid=`ipfs-cluster-ctl --host /dns4/cluster0/tcp/9094 id | grep -o -E "^(\w+)"`
          sleep 10
          cmd="daemon --bootstrap /dns4/cluster0/tcp/9096/ipfs/$$pid"
        fi
        /usr/local/bin/entrypoint.sh $$cmd
      '	  
##################################################################################
##################################################################################
## Cluster PEER 3 ################################################################
##################################################################################
      
  ipfs3:
    container_name: ipfs3
    image: ipfscors:1.0
    ports:
          - "4301:4001" # ipfs swarm
          - "4302:4002/udp" # udp swarm
#         - "5101:5001" # expose if needed/wanted
#         - "8180:8080" # exposes if needed/wanted
    volumes:
      - ./compose/ipfs3:/data/ipfs

  # cluster1 bootstraps to cluster0 if not bootstrapped before
  cluster3:
    container_name: cluster3
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - cluster0
      - ipfs3
    environment:
      # Change this! Same for all peers!
      CLUSTER_SECRET: adc72159e0ce63350c13de6a5e4d3b2f500232a770cb8c3e7829fc514d89d111
      IPFS_API: /dns4/ipfs3/tcp/5001
    ports:
          - "9394:9094" # API
#         - "9196:9096" # Cluster IPFS Proxy endpoint
    volumes:
      - ./compose/cluster3:/data/ipfs-cluster
    entrypoint:
      - "/sbin/tini"
      - "--"
    # Translation: if state folder does not exist, find cluster0 id and bootstrap
    # to it.
    command: >
      sh -c '
        cmd="daemon --upgrade"
        if [ ! -d /data/ipfs-cluster/raft ]; then
          while ! ipfs-cluster-ctl --host /dns4/cluster0/tcp/9094 id; do
            sleep 1
          done
          pid=`ipfs-cluster-ctl --host /dns4/cluster0/tcp/9094 id | grep -o -E "^(\w+)"`
          echo pid
          sleep 10
          cmd="daemon --bootstrap /dns4/cluster0/tcp/9096/ipfs/$$pid"
        fi
        /usr/local/bin/entrypoint.sh $$cmd
      '
# For adding more peers, copy PEER 1 and rename things to ipfs2, cluster2.
# Keep bootstrapping to cluster0.

##################################################################################
##################################################################################
## Cluster PEER 4 ################################################################
##################################################################################
      
  ipfs4:
    container_name: ipfs4
    image: ipfscors:1.0
    ports:
          - "4401:4001" # ipfs swarm
          - "4402:4002/udp" # udp swarm
#         - "5101:5001" # expose if needed/wanted
#         - "8180:8080" # exposes if needed/wanted
    volumes:
      - ./compose/ipfs4:/data/ipfs

  # cluster1 bootstraps to cluster0 if not bootstrapped before
  cluster4:
    container_name: cluster4
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - cluster0
      - ipfs4
    environment:
      # Change this! Same for all peers!
      CLUSTER_SECRET: adc72159e0ce63350c13de6a5e4d3b2f500232a770cb8c3e7829fc514d89d111
      IPFS_API: /dns4/ipfs4/tcp/5001
    ports:
          - "9494:9094" # API
#         - "9196:9096" # Cluster IPFS Proxy endpoint
    volumes:
      - ./compose/cluster4:/data/ipfs-cluster
    entrypoint:
      - "/sbin/tini"
      - "--"
    # Translation: if state folder does not exist, find cluster0 id and bootstrap
    # to it.
    command: >
      sh -c '
        cmd="daemon --upgrade"
        if [ ! -d /data/ipfs-cluster/raft ]; then
          while ! ipfs-cluster-ctl --host /dns4/cluster0/tcp/9094 id; do
            sleep 1
          done
          pid=`ipfs-cluster-ctl --host /dns4/cluster0/tcp/9094 id | grep -o -E "^(\w+)"`
          sleep 10
          cmd="daemon --bootstrap /dns4/cluster0/tcp/9096/ipfs/$$pid"
        fi
        /usr/local/bin/entrypoint.sh $$cmd
      '